# set -g @plugin 'tmux-plugins/tpm'
# set -g @plugin 'tmux-plugins/tmux-sensible'
# set -s default-terminal 'tmux-256color'

# set -g @plugin 'tmux-plugins/tmux-resurrect'
# set -g @plugin 'tmux-plugins/tmux-continuum'

set-option -g default-shell /usr/bin/bash

# run '~/.tmux/plugins/tpm/tpm'
