[FileDialog]
history=file:///home/vaclav/mounted/Movie, file:///home/vaclav/Downloads, file:///home/vaclav, "file:///home/vaclav/git/gimbal_simulator/ros2/gimbal_simulator/tmux ", file:///home/vaclav/tacq_records
lastVisited=file:///home/vaclav/tacq_records
qtVersion=6.11.1
shortcuts=file:, file:///home/vaclav
sidebarWidth=87
treeViewHeader="@ByteArray(\0\0\0\xff\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1\xd1\0\0\0\x4\x1\x1\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x64\xff\xff\xff\xff\0\0\0\x81\0\0\0\0\0\0\0\x4\0\0\0\xf5\0\0\0\x1\0\0\0\0\0\0\0\x39\0\0\0\x1\0\0\0\0\0\0\0=\0\0\0\x1\0\0\0\0\0\0\0\x66\0\0\0\x1\0\0\0\0\0\0\x3\xe8\0\xff\xff\xff\xff\0\0\0\0\0\0\0\0\0\0\0\0\0\0\0\x1)"
viewMode=Detail
