
[[Snippets]]
  Description = "Crop image - Command croppes the image using formula crop=width:height:w_start:h_start."
  Output = ""
  Tag = []
  command = "ffmpeg -i input.png -vf crop=500:500:0:0 output.png"

[[Snippets]]
  Description = "Get general file information - in case of images it will return size and coding."
  Output = ""
  Tag = []
  command = "file image.png"

[[Snippets]]
  Description = "Change resolution of the image, scale=800:-1 will shrink images width to 800 and respects original ratio. Scale=1024x768 will change ratio of the image."
  Output = ""
  Tag = []
  command = "ffmpeg -i input.png -vf scale=800:-1 output.png"

[[Snippets]]
  Description = "Secure copy from local to remote"
  Output = ""
  Tag = []
  command = "scp gurobi.lic mrs@gigabedna:/home/mrs/vaclav_ws/tsp/."

[[Snippets]]
  Description = "Tmux attaching to existing session."
  Output = ""
  Tag = []
  command = "tmux a -t <NUMBER>"

[[Snippets]]
  Description = "Secure copy file from remote device to yours."
  Output = ""
  Tag = []
  command = "scp mrs@gigabedna:/home/mrs/vaclav_ws/tsp/ktsp-pmm/python/tsp_result_b.txt /home/vaclav/."

[[Snippets]]
  Description = "Get information about image."
  Output = ""
  Tag = []
  command = "ffprobe image.png"

[[Snippets]]
  Description = "Wireguard activation - VPN on"
  Output = ""
  Tag = []
  command = "sudo wg-quick up wg0"

[[Snippets]]
  Description = "Wireguard deactivation - VPN off"
  Output = ""
  Tag = []
  command = "wg-quick down wg0"

[[Snippets]]
  Description = "Compression of mp4 video. Adjustable parameter by number N=20-34. The larger the number, the more compressed video output is."
  Output = ""
  Tag = []
  command = "ffmpeg -i input.mp4 -vcodec libx265 -crf 28 output.mp4"

[[Snippets]]
  Description = "Interface configuration - to get ip adresses, net masks. Optional parameter -a"
  Output = ""
  Tag = []
  command = "ifconfig"

[[Snippets]]
  Description = "Internet configuration - dedicated to wireless networking interfaces"
  Output = ""
  Tag = []
  command = "iwconfig"

[[Snippets]]
  Description = "Turn off the wifi"
  Output = ""
  Tag = []
  command = "sudo ip link set wlan0 down"

[[Snippets]]
  Description = "Turn on the wifi"
  Output = ""
  Tag = []
  command = "sudo ip link set wlan0 up"

[[Snippets]]
  Description = "Network scan - scan local network for device IP adresses."
  Output = ""
  Tag = []
  command = "sudo arp-scan --localnet"

[[Snippets]]
  Description = "Attach tmux session - with session socket/name."
  Output = ""
  Tag = []
  command = "tmux -L <tmux_session name> a"

[[Snippets]]
  Description = "MRS system params - custom_config.yaml configuration. Command copies all possible params into tmp directory."
  Output = ""
  Tag = []
  command = "rosrun mrs_uav_core get_public_params.py > /tmp/params.yaml"

[[Snippets]]
  Description = "Set up power10k - command line design."
  Output = ""
  Tag = []
  command = "p10k configure"

[[Snippets]]
  Description = "Wifi connection setup in command line"
  Output = ""
  Tag = []
  command = "nmtui"

[[Snippets]]
  Description = "Check current audio devices on PC."
  Output = ""
  Tag = []
  command = "wpctl status"

[[Snippets]]
  Description = "Change default audio device - First step: Check for sink_id of device running wpctl status. Step 2: call this command with proper sink_id. Step 3: Profit."
  Output = ""
  Tag = []
  command = "wpctl set-default <sink_id>"

[[Snippets]]
  Description = "How to create symlink"
  Output = ""
  Tag = []
  command = "ln -s /path/to/directory /path/to/symlink"

[[Snippets]]
  Description = "Ethernet network configuration via ifconfig - netmask and ip adress."
  Output = ""
  Tag = []
  command = "sudo ifconfig enp0s31f6 10.10.100.5/24"

[[Snippets]]
  Description = "Start recording display - cropped by using command tool slurp."
  Output = ""
  Tag = []
  command = "wf-recorder -g 915,287 282x139 -f vyrez.mp4"

[[Snippets]]
  Description = "Network manager disable operating with ethernet configuration - mandatory step before configuring ethernet connection via ifconfig."
  Output = ""
  Tag = []
  command = "sudo nmcli device set enp0s31f6 managed no"

[[Snippets]]
  Description = "TMUX sessions check over ALL sockets - tmux ls does not see all sessions, just the default... so check always if non-default exists."
  Output = ""
  Tag = []
  command = "ls -la /tmp/tmux-1000/"
