[General]
MainWindow.buttonActivateGrid=true
MainWindow.buttonLink=true
MainWindow.buttonRatio=false
MainWindow.buttonShowpoint=false
MainWindow.legendStatus=2
MainWindow.mainSplitterState=@ByteArray(\0\0\0\xff\0\0\0\x1\0\0\0\x2\0\0\x1\x18\0\0\x2\x6\0\0\0\0\x1\x1\0\0\0\x1\0)
MainWindow.streamingBufferValue=7
MainWindow.streamingSource=ROS 2 Topic Subscriber
MainWindow.timeTrackerSetting=1
MainWindow.useTimeOffset=false
previousFunnyMemesList=meme_25.jpg, meme_15.jpg, meme_27.jpg, meme_11.jpg, meme_23.jpg, meme_03.jpg, meme_13.jpg, meme_04.jpg, meme_26.jpg, meme_32.jpg

[DialogGeometry]
PlotJuggler%20Bridge=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\v\xc8\0\0\0\xea\0\0\r\t\0\0\x3\x41\0\0\v\xc8\0\0\0\xea\0\0\r\t\0\0\x3\x41\0\0\0\x1\0\0\0\0\n\0\0\0\v\xc8\0\0\0\xea\0\0\r\t\0\0\x3\x41)
ROS%202%20Topic%20Subscriber=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\n\xbb\0\0\x1\x94\0\0\xe\x43\0\0\x4\x35\0\0\n\xbb\0\0\x1\x94\0\0\xe\x43\0\0\x4\x35\0\0\0\x1\0\0\0\0\n\0\0\0\n\xbb\0\0\x1\x94\0\0\xe\x43\0\0\x4\x35)
WebRTC%20Video%20Client=@ByteArray(\x1\xd9\xd0\xcb\0\x3\0\0\0\0\vI\0\0\x1\xa7\0\0\r\xb6\0\0\x4!\0\0\vI\0\0\x1\xa7\0\0\r\xb6\0\0\x4!\0\0\0\x1\0\0\0\0\n\0\0\0\vI\0\0\x1\xa7\0\0\r\xb6\0\0\x4!)

[FileLoader]
lastDir=/home/vaclav/tacq_records

[PluginConfig]
Dummy%20Streamer=
ROS%202%20Topic%20Subscriber="{\"parser_config\":{\"array_policy\":\"clamp\",\"boolean_strings_to_number\":false,\"clamp_large_arrays\":true,\"discard_large_arrays\":false,\"max_array_size\":500,\"remove_suffix_from_strings\":false,\"use_embedded_timestamp\":false},\"selected_topics\":[{\"name\":\"/gimbal/attitude_rate\",\"type\":\"geometry_msgs/msg/Vector3Stamped\"},{\"name\":\"/gimbal/attitude_rate_cmd\",\"type\":\"geometry_msgs/msg/Vector3Stamped\"},{\"name\":\"/gimbal/quaternion\",\"type\":\"geometry_msgs/msg/QuaternionStamped\"},{\"name\":\"/gimbal/torque_cmd\",\"type\":\"geometry_msgs/msg/Vector3Stamped\"},{\"name\":\"/parameter_events\",\"type\":\"rcl_interfaces/msg/ParameterEvent\"},{\"name\":\"/rosout\",\"type\":\"rcl_interfaces/msg/Log\"}]}"
